version: "3.9"

services:
  db:
    container_name: db
    hostname: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  chatbot:
    container_name: chatbot
    image: chatbot
    restart: always
    build: .
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=dev
      - FLASK_APP=api
      - MY_SECRET_KEY=***REMOVED***
      - FYEO_PASSWORD=***REMOVED***
      - DATABASE_URL_DEV=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
      
    
volumes:
  pgdata: {}

#COMMANDS TO RUN APP IN DEV ENV
#docker-compose -f docker-compose-dev.yml up
#docker-compose -f docker-compose-dev.yml up --build
#docker-compose -f docker-compose-dev.yml down