services:
  chatbot:
    container_name: chatbot
    image: chatbot
    restart: always
    build: .
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=${FLASK_APP}
      - MY_SECRET_KEY=${MY_SECRET_KEY}
      - FYEO_PASSWORD=${FYEO_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GIT_TOKEN=${GIT_TOKEN}
      - CHATBOT_MODE=${CHATBOT_MODE}
      - DB_MODE=production
      - DB_MIGRATE=False
