version: "3.9"

services:
  chatbot:
    container_name: chatbot
    image: chatbot
    restart: always
    build: .
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=dev
      - FLASK_APP=api
      - MY_SECRET_KEY=***REMOVED***
      - FYEO_PASSWORD=***REMOVED***
      - DATABASE_URL=***REMOVED***
