services:
  db:
    container_name: db
    hostname: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  chatbot:
    container_name: chatbot
    image: chatbot
    restart: always
    build: .
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=dev
      - FLASK_APP=api
      - MY_SECRET_KEY=${MY_SECRET_KEY}
      - FYEO_PASSWORD=${FYEO_PASSWORD}
      - DATABASE_URL_DEV=${DATABASE_URL_DEV}
      - GIT_TOKEN=${GIT_TOKEN}
      - CHATBOT_MODE=${CHATBOT_MODE}
      - DB_MODE=dev
      - DB_MIGRATE=False
      - DB_INIT=False
    depends_on:
      - db
      
    
volumes:
  pgdata: {}

#COMMANDS TO RUN APP IN DEV ENV
#docker-compose -f docker-compose-dev.yml up
#docker-compose -f docker-compose-dev.yml up --build
#docker-compose -f docker-compose-dev.yml down